SELECTION_ENDPOINT_CODE = "POST_DECISION_SELECTION"
SESSION_START_ENDPOINT_CODE = "PATCH_WORKOUT_SESSION_START"
SESSION_STOP_ENDPOINT_CODE = "PATCH_WORKOUT_SESSION_STOP"
SESSION_ITEM_ENDPOINT_CODE = "PATCH_WORKOUT_SESSION_ITEM"
TIMER_EVENT_ENDPOINT_CODE = "POST_WORKOUT_TIMER_EVENT"
ADDITIONAL_ACTIVITY_ENDPOINT_CODE = "POST_WORKOUT_ADDITIONAL_ACTIVITY"
SAFETY_EVENT_ENDPOINT_CODE = "POST_WORKOUT_SAFETY_EVENT"
SESSION_FINISH_ENDPOINT_CODE = "PATCH_WORKOUT_SESSION_FINISH"
SESSION_NOT_COMPLETED_ENDPOINT_CODE = "PATCH_WORKOUT_SESSION_NOT_COMPLETED"
FEEDBACK_ENDPOINT_CODE = "POST_WORKOUT_FEEDBACK"
WORKOUT_RESPONSE_SCHEMA_VERSION = "workout-response-v1"

TERMINAL_SESSION_STATUS_CODES = frozenset(
    {"COMPLETED", "PARTIAL", "NOT_COMPLETED", "STOPPED_FOR_SAFETY"}
)

__all__ = [
    "ADDITIONAL_ACTIVITY_ENDPOINT_CODE",
    "FEEDBACK_ENDPOINT_CODE",
    "SAFETY_EVENT_ENDPOINT_CODE",
    "SELECTION_ENDPOINT_CODE",
    "SESSION_ITEM_ENDPOINT_CODE",
    "SESSION_FINISH_ENDPOINT_CODE",
    "SESSION_NOT_COMPLETED_ENDPOINT_CODE",
    "SESSION_START_ENDPOINT_CODE",
    "SESSION_STOP_ENDPOINT_CODE",
    "TERMINAL_SESSION_STATUS_CODES",
    "TIMER_EVENT_ENDPOINT_CODE",
    "WORKOUT_RESPONSE_SCHEMA_VERSION",
]
