import { createContext, useContext } from 'react';
import { Platform, StyleSheet } from 'react-native';

import { colors } from '../../components/theme';
import { fontFamilies } from '../../app/fonts';
import { createHomeSheetStyles } from './homeSheetStyles';

export function createHomeStyles(
  s: (value: number) => number,
  f: (value: number) => number,
  topPadding: number,
) {
  const shadow = (y: number, blur: number, opacity: number) => ({
    ...Platform.select({
      ios: {
        shadowColor: '#5A4636',
        shadowOffset: { width: 0, height: s(y) },
        shadowOpacity: opacity,
        shadowRadius: s(blur / 2),
      },
      android: { elevation: y <= 4 ? 2 : 3 },
      default: {
        shadowColor: '#5A4636',
        shadowOffset: { width: 0, height: s(y) },
        shadowOpacity: opacity,
        shadowRadius: s(blur / 2),
      },
    }),
  });
  return StyleSheet.create({
    screen: { flex: 1, overflow: 'hidden', backgroundColor: '#FFF8E5' },
    gradient: { flex: 1 },
    scroll: { flex: 1 },
    scrollContent: {
      paddingTop: topPadding,
      paddingHorizontal: s(18),
      paddingBottom: s(14),
    },
    header: {
      zIndex: 40,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: s(12),
      paddingTop: s(4),
      paddingHorizontal: s(4),
      paddingBottom: s(12),
    },
    headerCopy: { minWidth: 0, flex: 1 },
    greeting: {
      color: '#5A4636',
      fontSize: f(22),
      fontWeight: '800',
      lineHeight: f(27.5),
      textShadowColor: 'rgba(47,82,51,.18)',
      textShadowOffset: { width: 0, height: s(1) },
      textShadowRadius: s(2),
    },
    greetingName: { color: colors.greenText },
    greetingJua: { fontFamily: fontFamilies.slogan, fontWeight: '400' },
    date: {
      marginTop: s(3),
      color: colors.text,
      fontSize: f(13),
      fontWeight: '600',
      opacity: 0.95,
    },
    headerActions: {
      position: 'relative',
      zIndex: 50,
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(10),
    },
    notificationButton: {
      position: 'relative',
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: s(14),
      backgroundColor: colors.text,
      ...shadow(4, 10, 0.14),
    },
    notificationDot: {
      position: 'absolute',
      top: s(8),
      right: s(8),
      width: s(9),
      height: s(9),
      borderRadius: s(4.5),
      borderWidth: s(1.5),
      borderColor: colors.surface,
      backgroundColor: '#E9503F',
    },
    notificationToast: {
      position: 'absolute',
      top: topPadding + s(64),
      right: s(24),
      left: s(24),
      zIndex: 30,
      alignItems: 'center',
      borderWidth: s(1),
      borderColor: colors.successBorder,
      borderRadius: s(16),
      backgroundColor: colors.surface,
      paddingVertical: s(12),
      paddingHorizontal: s(18),
      ...shadow(5, 12, 0.16),
    },
    notificationToastText: {
      color: colors.text,
      fontSize: f(14),
      fontWeight: '800',
    },
    hidden: { display: 'none' },
    profileButton: {
      width: s(48),
      height: s(48),
      overflow: 'hidden',
      borderRadius: s(24),
      backgroundColor: '#FFFFFF',
      ...shadow(4, 12, 0.18),
    },
    profileAvatar: { width: '100%', height: '100%' },
    disabledControl: {
      opacity: 0.42,
    },
    disabledAction: {
      borderColor: '#D8D5D1',
      backgroundColor: '#F2F1EF',
    },
    disabledLabel: {
      color: '#98948E',
    },
    cardTitle: { color: '#5A4636', fontSize: f(15), fontWeight: '800' },
    greenText: { color: '#A45F00' },
    weekRow: { flexDirection: 'row', gap: s(6), marginTop: s(14) },
    weekDay: { minWidth: 0, flex: 1, alignItems: 'center', gap: s(3) },
    weekCircle: {
      width: s(32),
      height: s(32),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(2),
      borderRadius: s(16),
    },
    weekCircleCompleted: { borderColor: '#F6BA50', backgroundColor: '#F6BA50' },
    weekCircleIncomplete: {
      borderColor: '#D8D4CB',
      borderStyle: 'dashed',
      backgroundColor: '#FFFFFF',
    },
    weekMascot: { width: '92%', height: '92%' },
    weekLabel: { fontSize: f(11.5), fontWeight: '700' },
    weekLabelCompleted: { color: '#A45F00' },
    weekLabelIncomplete: { color: '#B0ACA4' },
    progressCard: {
      marginBottom: s(14),
      borderRadius: s(22),
      backgroundColor: '#FFFFFF',
      paddingTop: s(13),
      paddingHorizontal: s(16),
      paddingBottom: s(14),
      ...shadow(6, 18, 0.1),
    },
    progressHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: s(6),
    },
    progressTitleRow: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(2),
    },
    iconButton: { alignItems: 'center', justifyContent: 'center' },
    weekRange: { color: '#958476', fontSize: f(12), fontWeight: '600' },
    tip: {
      marginTop: s(10),
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
      paddingVertical: s(10),
      paddingHorizontal: s(12),
    },
    tipText: { color: '#4A5B44', fontSize: f(12.5), lineHeight: f(18.75) },
    countRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: s(10),
      marginTop: s(14),
    },
    countLabel: { color: '#5A4636', fontSize: f(15), fontWeight: '800' },
    countValue: { color: '#A45F00', fontSize: f(15) },
    completedCountValue: { color: '#A45F00', fontSize: f(22) },
    progressPercent: { color: '#A45F00', fontSize: f(22), fontWeight: '800' },
    checkinButton: { height: Math.max(44, s(52)) },
    checkinWrapper: { marginBottom: s(16) },
    messageCard: {
      alignItems: 'center',
      marginBottom: s(16),
      borderRadius: s(24),
      backgroundColor: '#FFFFFF',
      paddingVertical: s(22),
      paddingHorizontal: s(20),
      ...shadow(6, 18, 0.1),
    },
    messageCardAction: { alignSelf: 'stretch', marginTop: s(14) },
    messageTitle: {
      color: '#5A4636',
      fontSize: f(15),
      fontWeight: '800',
      textAlign: 'center',
    },
    messageText: {
      marginTop: s(8),
      color: '#958476',
      fontSize: f(13),
      lineHeight: f(19.5),
      textAlign: 'center',
    },
    routineSetupLoadingTitle: { marginTop: s(12) },
    routineSetupAction: {
      alignSelf: 'stretch',
      marginTop: s(20),
    },
    routineSetupButtonLabel: {
      color: '#35512E',
      fontSize: f(18),
      fontWeight: '800',
    },
    routineCard: {
      position: 'relative',
      overflow: 'hidden',
      marginBottom: s(16),
      borderRadius: s(24),
      backgroundColor: '#FFFFFF',
      paddingTop: s(18),
      paddingHorizontal: s(18),
      paddingBottom: s(8),
      ...shadow(6, 18, 0.1),
    },
    routineBadgeRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: s(8),
    },
    routineBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      backgroundColor: '#F6BA50',
      paddingVertical: s(6),
      paddingHorizontal: s(12),
    },
    routineBadgeText: { color: '#5A4636', fontSize: f(12), fontWeight: '700' },
    routineActionBadge: {
      alignSelf: 'flex-start',
      borderWidth: s(1.5),
      borderColor: '#F1D39A',
      borderRadius: 999,
      backgroundColor: '#FFFFFF',
      paddingVertical: s(4.5),
      paddingHorizontal: s(11),
    },
    routineActionBadgeAdjusted: {
      borderColor: '#F6BA50',
      backgroundColor: '#FFF8E5',
    },
    routineActionBadgeText: {
      color: '#A45F00',
      fontSize: f(12),
      fontWeight: '700',
    },
    routineTitle: {
      marginTop: s(12),
      color: '#5A4636',
      fontSize: f(26),
      fontWeight: '800',
      letterSpacing: s(-0.5),
    },
    routinePlanName: {
      marginTop: s(8),
      color: '#5A4636',
      fontSize: f(15),
      fontWeight: '700',
    },
    routineSummary: {
      marginTop: s(10),
      color: '#A45F00',
      fontSize: f(14),
      fontWeight: '700',
    },
    routineNotes: { gap: s(4), marginTop: s(10) },
    routineNote: {
      color: '#7B695B',
      fontSize: f(13.5),
      fontWeight: '500',
      lineHeight: f(20.925),
    },
    reasonLink: {
      alignSelf: 'flex-start',
      minHeight: s(40),
      justifyContent: 'center',
      marginTop: s(2),
      paddingRight: s(12),
    },
    reasonLinkText: {
      color: '#A45F00',
      fontSize: f(12.5),
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    routineList: {
      gap: s(8),
      marginTop: s(14),
      borderTopWidth: s(1),
      borderTopColor: '#E8D8C2',
      borderStyle: 'dashed',
      paddingTop: s(12),
    },
    routineLoadingSlot: {
      minHeight: s(220),
      overflow: 'hidden',
      marginTop: s(14),
      marginBottom: s(4),
      borderTopWidth: s(1),
      borderTopColor: '#E8D8C2',
      borderStyle: 'dashed',
      borderRadius: s(16),
      backgroundColor: 'rgba(255, 248, 229, 0.62)',
      padding: s(10),
    },
    routineLoadingPreview: {
      width: '100%',
      opacity: 0.34,
    },
    routineLoadingRow: {
      minHeight: s(46),
      justifyContent: 'center',
      borderRadius: s(12),
      backgroundColor: '#F3ECE4',
      paddingHorizontal: s(12),
    },
    routineLoadingPlaceholderLine: {
      width: '68%',
      height: s(10),
      borderRadius: 999,
      backgroundColor: '#CDBEAF',
    },
    orderHint: {
      color: '#A29B8E',
      fontSize: f(11.5),
      fontWeight: '700',
      letterSpacing: s(0.23),
    },
    dragOuterRoutine: {
      position: 'relative',
      borderWidth: s(1.5),
      borderColor: 'transparent',
      borderRadius: s(12),
      backgroundColor: 'transparent',
    },
    dropPlaceholder: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderWidth: s(1.5),
      borderColor: '#E0A742',
      borderRadius: s(12),
      borderStyle: 'dashed',
      backgroundColor: '#FFF3D4',
    },
    dragOuterEdit: {
      position: 'relative',
      borderWidth: s(1.5),
      borderColor: 'transparent',
      borderRadius: s(16),
      backgroundColor: 'transparent',
    },
    dragOuterActive: {
      zIndex: 10,
      elevation: 4,
    },
    routineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(10),
      borderRadius: s(11),
      backgroundColor: 'transparent',
      paddingVertical: s(7),
      paddingHorizontal: s(8),
    },
    dragInnerRoutineActive: {
      zIndex: 6,
      backgroundColor: '#FFFFFF',
      ...shadow(10, 20, 0.22),
    },
    dragInnerEditActive: { zIndex: 6, opacity: 0.97, ...shadow(10, 20, 0.22) },
    routineHandle: {
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: s(-11),
      marginRight: 0,
      marginBottom: s(-11),
      marginLeft: s(-8),
    },
    routineItemText: {
      minWidth: 0,
      flex: 1,
      color: '#5A4636',
      fontSize: f(13.5),
      fontWeight: '700',
      lineHeight: f(19.575),
    },
    routineItemCompleted: {
      color: '#AAA49D',
    },
    routineRowCompleted: {
      backgroundColor: '#F4F2EF',
      opacity: 0.68,
    },
    inlinePrescriptionRow: {
      minWidth: 0,
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(5),
    },
    inlinePrescriptionRowEditing: {
      gap: s(2),
    },
    inlineExerciseName: {
      minWidth: 0,
      flex: 1,
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
    },
    inlineExerciseNameEditing: {
      minWidth: s(50),
    },
    inlinePrescriptionInput: {
      width: s(34),
      borderWidth: s(1),
      borderColor: '#E0A742',
      borderRadius: s(9),
      backgroundColor: '#FFFDF8',
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
      paddingHorizontal: s(2),
      paddingVertical: s(7),
      textAlign: 'center',
    },
    inlinePrescriptionInputEditing: {
      width: s(28),
    },
    inlinePrescriptionUnit: {
      color: '#8B8178',
      fontSize: f(11),
      fontWeight: '700',
    },
    inlinePrescriptionUnitEditing: {
      fontSize: f(9.5),
    },
    routineGuideActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(4),
    },
    routineGuideActionsEditing: {
      gap: s(2),
    },
    routineGuideSlot: {
      width: s(48),
      height: s(32),
      alignItems: 'center',
      justifyContent: 'center',
    },
    routineGuideSlotEditing: {
      width: s(44),
    },
    routineGuideButton: {
      width: s(48),
      height: s(32),
      minHeight: s(32),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#C8D7AC',
      borderRadius: s(999),
      backgroundColor: '#EDF3DD',
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    routineGuideButtonText: {
      color: '#5F7048',
      fontSize: f(11.5),
      fontWeight: '700',
    },
    routineGuideButtonDisabled: {
      borderColor: '#D8D5D1',
      backgroundColor: '#F2F1EF',
    },
    routineGuideButtonEditing: {
      width: s(44),
    },
    routineGuideButtonTextEditing: {
      fontSize: f(9.5),
    },
    routineEquipmentButton: {
      borderColor: '#9CC5DF',
      backgroundColor: '#E7F3FA',
    },
    routineEquipmentButtonText: {
      color: '#356A85',
      fontSize: f(11.5),
      fontWeight: '700',
    },
    adjustmentNote: {
      marginTop: s(12),
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
      paddingVertical: s(10),
      paddingHorizontal: s(12),
    },
    adjustmentText: {
      color: '#4A5B44',
      fontSize: f(12.5),
      lineHeight: f(18.75),
    },
    startButton: {
      width: '100%',
      minHeight: s(58),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      marginTop: s(16),
      marginBottom: s(10),
      borderWidth: s(1),
      borderColor: 'rgba(218, 150, 30, 0.2)',
      borderRadius: s(18),
      overflow: 'hidden',
      paddingVertical: s(16),
      paddingHorizontal: s(20),
      ...shadow(6, 12, 0.13),
    },
    startButtonDisabled: {
      borderColor: '#DDD4CA',
      shadowOpacity: 0,
      elevation: 0,
    },
    startButtonGradient: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    startLabel: {
      color: '#5A4636',
      fontSize: f(17),
      fontWeight: '800',
      letterSpacing: s(-0.1),
      textAlign: 'center',
    },
    startLabelDisabled: {
      color: '#9C9892',
    },
    routineActions: {
      flexDirection: 'row',
      gap: s(8),
      marginTop: s(8),
      marginBottom: s(10),
    },
    routineAction: {
      minWidth: 0,
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: s(6),
      borderWidth: s(1.5),
      borderColor: '#F1D39A',
      borderRadius: s(16),
      backgroundColor: '#FFFFFF',
      paddingVertical: s(14),
      paddingHorizontal: s(6),
    },
    routineActionDisabled: { borderColor: '#EEDFCB' },
    editActionLabel: { color: '#A45F00', fontSize: f(13.5), fontWeight: '700' },
    restAction: {
      position: 'relative',
      alignSelf: 'stretch',
      flex: 0,
      minHeight: s(50),
      borderWidth: s(1),
      borderColor: '#BFD09F',
      borderRadius: s(16),
      backgroundColor: '#F4F8E9',
      overflow: 'hidden',
      paddingVertical: s(12),
      paddingHorizontal: s(18),
      ...shadow(3, 8, 0.07),
    },
    restActionDisabled: {
      borderColor: '#D8D5D1',
      shadowOpacity: 0,
      elevation: 0,
    },
    restActionGradient: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    restActionIcon: {
      width: s(28),
      height: s(28),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#D5E2BD',
      borderRadius: s(999),
      backgroundColor: 'rgba(255, 255, 255, 0.72)',
    },
    restActionIconDisabled: {
      borderColor: '#DDDAD5',
      backgroundColor: 'rgba(255, 255, 255, 0.48)',
    },
    restActionLabel: {
      color: '#52653F',
      fontSize: f(14),
      fontWeight: '700',
      letterSpacing: s(-0.1),
    },
    rerollActionLabel: {
      color: '#A45F00',
      fontSize: f(12.5),
      fontWeight: '700',
    },
    rerollActionLabelDisabled: { color: '#B0ACA4' },
    ...createHomeSheetStyles(s, f),
  });
}

export type HomeStyles = ReturnType<typeof createHomeStyles>;
const fallbackHomeStyles = createHomeStyles(
  (value) => value,
  (value) => value,
  58,
);
export const HomeStyleContext = createContext<HomeStyles>(fallbackHomeStyles);

export function useHomeStyles() {
  return useContext(HomeStyleContext);
}
