import { TIME_WHEEL_ITEM_HEIGHT } from './homeConstants';
import { StyleSheet } from 'react-native';

export function createHomeSheetStyles(
  s: (value: number) => number,
  f: (value: number) => number,
) {
  return StyleSheet.create({
    sheetOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(20,32,16,.42)',
    },
    sheet: {
      width: '100%',
      maxHeight: '88%',
      borderTopLeftRadius: s(28),
      borderTopRightRadius: s(28),
      backgroundColor: '#FFF8E5',
      paddingTop: s(20),
      paddingHorizontal: s(18),
      paddingBottom: s(30),
    },
    checkinSheet: { paddingTop: s(14), paddingBottom: s(16) },
    checkinScrollContent: { gap: s(6), paddingTop: s(10), paddingBottom: s(5) },
    redFlagSymptoms: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      columnGap: s(12),
      rowGap: s(2),
    },
    durationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: s(8),
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: s(10),
    },
    sheetTitle: { color: '#5A4636', fontSize: f(18), fontWeight: '800' },
    sheetIntro: {
      marginTop: s(4),
      color: '#958476',
      fontSize: f(13),
      lineHeight: f(19.5),
    },
    reasonSheetContent: { gap: s(10), paddingTop: s(14), paddingBottom: s(5) },
    reasonSection: {
      gap: s(9),
      borderRadius: s(18),
      backgroundColor: '#FFFFFF',
      padding: s(16),
    },
    reasonRow: { flexDirection: 'row', alignItems: 'flex-start', gap: s(7) },
    reasonBullet: { color: '#F6BA50', fontSize: f(14), lineHeight: f(20) },
    reasonText: {
      minWidth: 0,
      flex: 1,
      color: '#7B695B',
      fontSize: f(13),
      lineHeight: f(19.5),
    },
    reasonDisclosureHeader: {
      minHeight: s(32),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: s(12),
    },
    reasonDisclosureAction: {
      color: '#A45F00',
      fontSize: f(12),
      fontWeight: '800',
    },
    agentSummary: { gap: s(4) },
    agentSummaryLabel: {
      color: '#A45F00',
      fontSize: f(12),
      fontWeight: '800',
    },
    sheetScrollContent: { gap: s(10), paddingTop: s(14), paddingBottom: s(5) },
    checkinSection: {
      borderRadius: s(14),
      backgroundColor: '#FFFFFF',
      paddingVertical: s(9),
      paddingHorizontal: s(14),
    },
    checkinSectionTitle: {
      color: '#5A4636',
      fontSize: f(14),
      fontWeight: '700',
    },
    choiceRow: { flexDirection: 'row', gap: s(6), marginTop: s(6) },
    choiceRowTwoColumn: { flexWrap: 'wrap' },
    choiceButton: {
      minWidth: 0,
      minHeight: Math.max(44, s(40)),
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1.5),
      borderColor: '#EEDFCB',
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
      paddingVertical: s(6),
      paddingHorizontal: s(6),
    },
    choiceButtonTwoColumn: {
      minHeight: Math.max(44, s(40)),
      flexBasis: '48%',
      flexGrow: 1,
    },
    choiceButtonSelected: {
      borderColor: '#F6BA50',
      backgroundColor: '#F6BA50',
    },
    choiceButtonText: { color: '#5A4636', fontSize: f(13), fontWeight: '700' },
    choiceButtonTextSelected: { color: '#5A4636' },
    extendedAreaToggle: {
      minHeight: s(36),
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: s(6),
      paddingHorizontal: s(8),
    },
    extendedAreaToggleLabel: {
      color: '#958476',
      fontSize: f(12),
      fontWeight: '600',
    },
    extendedAreaToggleIcon: {
      width: s(24),
      height: s(24),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(12),
      backgroundColor: '#FFFFFF',
    },
    extendedAreaToggleCaretUp: {
      transform: [{ rotate: '180deg' }],
    },
    painSliderCard: {
      borderWidth: s(1),
      borderColor: '#E8C3B8',
      borderRadius: s(14),
      backgroundColor: '#FFFDFC',
      paddingVertical: s(9),
      paddingHorizontal: s(14),
    },
    redFlagSection: {
      gap: s(4),
      borderWidth: s(1),
      borderColor: '#E8C3B8',
      borderRadius: s(14),
      backgroundColor: '#FBECE8',
      paddingVertical: s(10),
      paddingHorizontal: s(14),
    },
    redFlagTitle: {
      color: '#B04A2C',
      fontSize: f(15),
      fontWeight: '700',
    },
    redFlagBody: {
      color: '#B04A2C',
      fontSize: f(13),
      lineHeight: f(19),
    },
    numberRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: s(12),
      borderRadius: s(14),
      backgroundColor: '#FFFFFF',
      paddingVertical: s(9),
      paddingHorizontal: s(14),
    },
    numberLabel: { color: '#5A4636', fontSize: f(14), fontWeight: '700' },
    optionalText: { color: '#958476', fontWeight: '500' },
    durationStepper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(10),
    },
    durationStepButton: {
      width: Math.max(44, s(40)),
      height: Math.max(44, s(40)),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
    },
    durationStepButtonDisabled: { opacity: 0.4 },
    durationStepButtonText: {
      color: '#5A4636',
      fontSize: f(22),
      fontWeight: '800',
      lineHeight: f(24),
    },
    durationStepValue: {
      minWidth: s(46),
      color: '#5A4636',
      fontSize: f(15),
      fontWeight: '800',
      textAlign: 'center',
    },
    numberInputGroup: { flexDirection: 'row', alignItems: 'center', gap: s(6) },
    numberInput: {
      width: s(84),
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(14),
      fontWeight: '700',
      minHeight: 44,
      paddingVertical: s(7),
      paddingHorizontal: s(12),
      textAlign: 'right',
    },
    availabilitySection: {
      gap: s(10),
      borderRadius: s(18),
      backgroundColor: '#FFFFFF',
      padding: s(16),
    },
    availabilityHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(5),
    },
    availabilitySlotRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(8),
    },
    availabilityTimeButton: {
      flex: 1,
      minWidth: 0,
      minHeight: s(44),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
      paddingVertical: s(11),
      paddingHorizontal: s(10),
    },
    availabilityTimeText: {
      color: '#5A4636',
      fontSize: f(14),
      fontWeight: '700',
      textAlign: 'center',
    },
    availabilityTimePlaceholder: { color: '#AAA69F', fontWeight: '600' },
    availabilitySeparator: {
      color: '#958476',
      fontSize: f(15),
      fontWeight: '700',
    },
    availabilityRemoveButton: {
      width: s(28),
      height: s(42),
      alignItems: 'center',
      justifyContent: 'center',
    },
    availabilityAddButton: {
      minHeight: s(44),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1),
      borderColor: '#E0A742',
      borderStyle: 'dashed',
      borderRadius: s(12),
      backgroundColor: '#FFF8E5',
    },
    availabilityAddLabel: {
      color: '#A45F00',
      fontSize: f(13),
      fontWeight: '700',
    },
    availabilityHelpText: {
      color: '#958476',
      fontSize: f(12),
      lineHeight: f(18),
    },
    timePickerIntro: {
      marginTop: s(2),
      color: '#958476',
      fontSize: f(13),
      lineHeight: f(19),
    },
    timePickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(10),
      marginTop: s(16),
    },
    timePickerColon: {
      color: '#5A4636',
      fontSize: f(24),
      fontWeight: '800',
    },
    timeWheelColumn: {
      position: 'relative',
      minWidth: 0,
      height: TIME_WHEEL_ITEM_HEIGHT * 3,
      flex: 1,
      overflow: 'hidden',
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(14),
      backgroundColor: '#FFFFFF',
    },
    timeWheelScroll: { zIndex: 2 },
    timeWheelContent: { paddingVertical: TIME_WHEEL_ITEM_HEIGHT },
    timeWheelSelection: {
      position: 'absolute',
      top: TIME_WHEEL_ITEM_HEIGHT,
      right: s(5),
      left: s(5),
      height: TIME_WHEEL_ITEM_HEIGHT,
      borderRadius: s(9),
      backgroundColor: '#FFF3D4',
    },
    timeWheelItem: {
      height: TIME_WHEEL_ITEM_HEIGHT,
      alignItems: 'center',
      justifyContent: 'center',
    },
    timeWheelItemText: {
      color: '#958476',
      fontSize: f(17),
      fontWeight: '600',
    },
    timeWheelItemTextSelected: { color: '#A45F00', fontWeight: '800' },
    timeWheelItemSuffix: { fontSize: f(12), fontWeight: '600' },
    timePickerActions: {
      flexDirection: 'row',
      gap: s(10),
      marginTop: s(18),
    },
    timePickerConfirmButton: {
      minHeight: s(48),
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: s(14),
      backgroundColor: '#F6BA50',
    },
    timePickerConfirmLabel: {
      color: '#5A4636',
      fontSize: f(15),
      fontWeight: '800',
    },
    stepsInput: { width: s(110) },
    numberSuffix: { color: '#958476', fontSize: f(13) },
    sheetSaveButton: {
      position: 'relative',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0,
      borderWidth: s(1),
      borderColor: 'rgba(244, 166, 42, 0.8)',
      borderRadius: s(18),
      minHeight: Math.max(44, s(52)),
      paddingVertical: s(10),
      paddingHorizontal: s(17),
      shadowColor: '#AD741D',
      shadowOffset: { width: 0, height: s(5) },
      shadowOpacity: 0.11,
      shadowRadius: s(6),
      elevation: 3,
    },
    sheetSaveGradient: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderRadius: s(18),
    },
    sheetSaveLabel: { color: '#5A4636', fontSize: f(18), fontWeight: '800' },
    sheetSaveButtonDisabled: {
      borderColor: '#E3DAD0',
      shadowOpacity: 0,
      elevation: 0,
    },
    sheetSaveGradientDisabled: { opacity: 0.35 },
    sheetSaveLabelDisabled: { color: '#AFA69B' },
    editScrollContent: { paddingBottom: s(5) },
    editList: { gap: s(8), marginTop: s(14) },
    editRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(6),
      borderRadius: s(14),
      backgroundColor: '#FFFFFF',
      paddingTop: s(8),
      paddingRight: s(6),
      paddingBottom: s(8),
      paddingLeft: s(10),
    },
    editHandle: {
      width: s(26),
      height: s(40),
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: s(-4),
    },
    editNameInput: {
      minWidth: 0,
      flex: 1,
      color: '#5A4636',
      fontSize: f(13.5),
      fontWeight: '700',
      paddingVertical: s(6),
    },
    editSetsInput: {
      width: s(38),
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(10),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
      paddingVertical: s(8),
      paddingHorizontal: s(2),
      textAlign: 'center',
    },
    editRepsInput: {
      width: s(44),
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(10),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
      paddingVertical: s(8),
      paddingHorizontal: s(2),
      textAlign: 'center',
    },
    editUnit: { color: '#B0ACA4', fontSize: f(11.5), fontWeight: '700' },
    deleteButton: {
      width: s(32),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBox: {
      marginTop: s(12),
      borderWidth: s(1.5),
      borderColor: '#F1D39A',
      borderStyle: 'dashed',
      borderRadius: s(16),
      backgroundColor: '#FFFFFF',
      padding: s(12),
    },
    addTitle: { color: '#A45F00', fontSize: f(12), fontWeight: '700' },
    addInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(6),
      marginTop: s(8),
    },
    addNameInput: {
      minWidth: 0,
      flex: 1,
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(10),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(13.5),
      fontWeight: '700',
      padding: s(10),
    },
    addSetsInput: {
      width: s(38),
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(10),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
      paddingVertical: s(10),
      paddingHorizontal: s(2),
      textAlign: 'center',
    },
    addRepsInput: {
      width: s(44),
      borderWidth: s(1),
      borderColor: '#EEDFCB',
      borderRadius: s(10),
      backgroundColor: '#FFF8E5',
      color: '#5A4636',
      fontSize: f(13),
      fontWeight: '700',
      paddingVertical: s(10),
      paddingHorizontal: s(2),
      textAlign: 'center',
    },
    addButton: {
      width: '100%',
      marginTop: s(10),
      borderRadius: s(12),
      padding: s(12),
    },
    addButtonEnabled: { backgroundColor: '#F6BA50' },
    addButtonDisabled: { backgroundColor: '#EEDFCB' },
    addButtonText: {
      fontSize: f(13.5),
      fontWeight: '700',
      textAlign: 'center',
    },
    addButtonTextEnabled: { color: '#5A4636' },
    addButtonTextDisabled: { color: '#B0ACA4' },
    editActions: { flexDirection: 'row', gap: s(8), marginTop: s(16) },
    resetButton: {
      width: s(112),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: s(1.5),
      borderColor: '#EEDFCB',
      borderRadius: s(18),
      backgroundColor: '#FFFFFF',
      paddingVertical: s(16),
      paddingHorizontal: s(8),
    },
    resetLabel: { color: '#958476', fontSize: f(12.5), fontWeight: '700' },
    editSaveButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: s(5),
      borderBottomColor: '#D98B16',
      borderRadius: s(18),
      backgroundColor: '#F6BA50',
      padding: s(16),
    },
  });
}
