WEEKLY_PLAN_ENDPOINT_CODE = "POST_WEEKLY_PLAN"
WEEKLY_PLAN_REVISION_ENDPOINT_CODE = "POST_WEEKLY_PLAN_REVISION"
WEEKLY_PLAN_INPUT_SCHEMA_VERSION = "weekly-plan-input-v1"
WEEKLY_PLAN_RESPONSE_SCHEMA_VERSION = "weekly-plan-response-v1"


__all__ = [
    "WEEKLY_PLAN_ENDPOINT_CODE",
    "WEEKLY_PLAN_INPUT_SCHEMA_VERSION",
    "WEEKLY_PLAN_RESPONSE_SCHEMA_VERSION",
    "WEEKLY_PLAN_REVISION_ENDPOINT_CODE",
]
