WEEKLY_REPORT_ENDPOINT_CODE = "POST_WEEKLY_REPORT"
WEEKLY_REPORT_ACK_ENDPOINT_CODE = "POST_WEEKLY_REPORT_ACKNOWLEDGEMENT"
WEEKLY_REPORT_INPUT_SCHEMA_VERSION = "weekly-report-input-v1"
WEEKLY_REPORT_POLICY_VERSION = "weekly-report-policy-v1"
WEEKLY_REPORT_RESPONSE_SCHEMA_VERSION = "weekly-report-response-v1"

__all__ = [
    "WEEKLY_REPORT_ACK_ENDPOINT_CODE",
    "WEEKLY_REPORT_ENDPOINT_CODE",
    "WEEKLY_REPORT_INPUT_SCHEMA_VERSION",
    "WEEKLY_REPORT_POLICY_VERSION",
    "WEEKLY_REPORT_RESPONSE_SCHEMA_VERSION",
]
