from enum import StrEnum

ACCOUNT_DELETION_POLICY_VERSION = "account-deletion-retention-v1"
ACCOUNT_DELETION_RESPONSE_SCHEMA_VERSION = "account-deletion-response-v1"
DELETION_ENDPOINT_CODE = "DELETE_ME"


class DeletionJobStatusCode(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_PENDING = "RETRY_PENDING"
    BACKUP_EXPIRY_PENDING = "BACKUP_EXPIRY_PENDING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_EXTERNAL_REVOCATION_FAILURE = "COMPLETED_WITH_EXTERNAL_REVOCATION_FAILURE"
    FAILED_REQUIRES_REVIEW = "FAILED_REQUIRES_REVIEW"


class DeletionStageCode(StrEnum):
    ACCESS_BLOCK = "ACCESS_BLOCK"
    EXTERNAL_REVOCATION = "EXTERNAL_REVOCATION"
    OPERATIONAL_DATA_DELETE = "OPERATIONAL_DATA_DELETE"
    CACHE_AND_WORK_DELETE = "CACHE_AND_WORK_DELETE"
    AUDIT_DEIDENTIFICATION = "AUDIT_DEIDENTIFICATION"
    BACKUP_EXPIRY_VERIFICATION = "BACKUP_EXPIRY_VERIFICATION"


class ExternalRevocationStatusCode(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    RETRY_PENDING = "RETRY_PENDING"
    FAILED_FINAL = "FAILED_FINAL"


class DeletionFailureCode(StrEnum):
    EXTERNAL_REVOCATION_RETRYABLE = "EXTERNAL_REVOCATION_RETRYABLE"
    EXTERNAL_REVOCATION_FINAL = "EXTERNAL_REVOCATION_FINAL"
    OPERATIONAL_DATA_DELETE_FAILED = "OPERATIONAL_DATA_DELETE_FAILED"
    BACKUP_EXPIRY_EVIDENCE_UNAVAILABLE = "BACKUP_EXPIRY_EVIDENCE_UNAVAILABLE"


__all__ = [
    "ACCOUNT_DELETION_POLICY_VERSION",
    "ACCOUNT_DELETION_RESPONSE_SCHEMA_VERSION",
    "DELETION_ENDPOINT_CODE",
    "DeletionFailureCode",
    "DeletionJobStatusCode",
    "DeletionStageCode",
    "ExternalRevocationStatusCode",
]
